1. Python program to add two Matrices?

In [3]:
x =  [[1,2,3],
      [4,5,6],
      [7,8,9]]
y =  [[9,8,7],
      [6,5,4],
      [3,2,1]]

result=[[0,0,0],
        [0,0,0],
        [0,0,0]]

for i in range(len(x)):
    for j in range(len(x[0])):
        result[i][j]=x[i][j]+y[i][j]
        
    for r in result:
        print(r)

[10, 10, 10]
[0, 0, 0]
[0, 0, 0]
[10, 10, 10]
[10, 10, 10]
[0, 0, 0]
[10, 10, 10]
[10, 10, 10]
[10, 10, 10]


2. Python program to multiply two matrices?

In [7]:
A = [[8,12,4],
     [6,4,5],
     [7,8,9]]
B = [[3,0,1,2],
     [6,7,8,9],
     [14,8,2,7]]
result = [[0,0,0,0],
          [0,0,0,0],
          [0,0,0,0]]
for i in range(len(A)):
    for j in range(len(B[0])):
        
         for k in range(len(B)):
            
            result[i][j]+=A[i][k] * B[k][j]
    
         for r in result:
            print(r)
        

[152, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[152, 116, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[152, 116, 112, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[152, 116, 112, 152]
[0, 0, 0, 0]
[0, 0, 0, 0]
[152, 116, 112, 152]
[112, 0, 0, 0]
[0, 0, 0, 0]
[152, 116, 112, 152]
[112, 68, 0, 0]
[0, 0, 0, 0]
[152, 116, 112, 152]
[112, 68, 48, 0]
[0, 0, 0, 0]
[152, 116, 112, 152]
[112, 68, 48, 83]
[0, 0, 0, 0]
[152, 116, 112, 152]
[112, 68, 48, 83]
[195, 0, 0, 0]
[152, 116, 112, 152]
[112, 68, 48, 83]
[195, 128, 0, 0]
[152, 116, 112, 152]
[112, 68, 48, 83]
[195, 128, 89, 0]
[152, 116, 112, 152]
[112, 68, 48, 83]
[195, 128, 89, 149]


3. Python program for Matrix Product?

In [9]:
import numpy as np
A = [[12, 7, 3], [4, 5, 6], [7, 8, 9]]
B = [[5, 8, 1, 2], [6, 7, 3, 0], [4, 5, 9, 1]]
result= [[0,0,0,0], [0,0,0,0], [0,0,0,0]]
result= np.dot(A,B)

for p in result:
    print(p)

[114 160  60  27]
[74 97 73 14]
[119 157 112  23]


4. Adding and Subtracting Matrices in Python?

In [4]:
import numpy as np
A=np.array([[6,4],[9,8]])
B=np.array([[10,14],[9,12]])
print("printing element of first matrix")
print(A)
print("printing element of second matrix")
print(B)
print("subtracting of two matrix")
print(np.subtract(A,B))


printing element of first matrix
[[6 4]
 [9 8]]
printing element of second matrix
[[10 14]
 [ 9 12]]
subtracting of two matrix
[[ -4 -10]
 [  0  -4]]


5. Transpose a matrix in Single line in Python?

In [5]:
import numpy
matrix=[[10,20,30],[25,32,44]]
print(matrix)
print("/n")
print(numpy.transpose(matrix))


[[10, 20, 30], [25, 32, 44]]
/n
[[10 25]
 [20 32]
 [30 44]]


6. Python | Matrix creation of n*n?

In [6]:
N=4
print("The dimension:"+ str(N))
res = [list(range(1+ N * i,1 + N * (i+1)))
       for i in range(N)]
print("The created matrix of N * N: "+str(res))

The dimension:4
The created matrix of N * N: [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]


7. Python | Get Kth Column of Matrix?

In [7]:
test_list=[[2,6,8,],[12,21,4],[18,2,24]]
print("The original list is: "+str(test_list))
k=2
res=[sub[k]for sub in test_list]
print("The kth coulmn of matrix is: "+str(res))

The original list is: [[2, 6, 8], [12, 21, 4], [18, 2, 24]]
The kth coulmn of matrix is: [8, 4, 24]


8. Python – Vertical Concatenation in Matrix?

In [10]:
test_list=[["fig","food"],["is","for"],["best"]]
print("The original list:"+str(test_list))
res=[]
N=0
while N !=len(test_list):
    temp= ' '
    for idx in test_list:
        try: temp = temp + idx[N]
        except IndexError: pass
        res.append(temp)
        N=N + 1
        res=[ele for ele in res if ele]
        print("list after column concatanation : "+str(res))

The original list:[['fig', 'food'], ['is', 'for'], ['best']]
list after column concatanation : [' fig']
list after column concatanation : [' fig', ' figfor']
list after column concatanation : [' fig', ' figfor', ' figfor']


9. Python program to check if a string is palindrome or not?

In [18]:
def ispalindrome(s):
    return s == s[::-1]
s="radar"
ans=ispalindrome(s)
if ans:
    print("Yes")
else:
    print("No")

Yes


10. Python program to check whether the string is Symmetrical or Palindrome?

In [24]:
string= 'amaama'
half= int(len(string /2)
          
          
if  len(string) % 2 == 0:
        first_str=string[:half]
        second_str=string[half:]
else:
          first_str=string[:half]
          second_str=string[half+1:]
          
if first_str == second_str:
          print(string,'string is symmetrical')
else:
          print(string,'string is not symmetrical')
          
if first_str == second_str[::-1]:
          print(string,'string is palindrome')
else:
          print(string,'string is not palindrome')
          
          
          
          

SyntaxError: invalid syntax (514367201.py, line 5)